### PR TITLE
Feature/browse tags

### PR DESCRIPTION
**Pull request by JorgenSolli**
Added the option for users to browse tags, without having to search for them.

I'm sure there will be some feedback with wanted changes before this is merged, but for now; this is a working 'prototype'

Preview:
image
image
image

### CODE REVIEW

**Comment by JorgenSolli** [comment]
> This looks quite good, thank you!
> 
> However, just as with #90, it needs to go to 3.3-release branch :)

Hi, @emodric 
No worries. I have changed the target branch now on both PRs :)

**Comment by emodric** [comment]
You will also need to rebase your commits to 3.3 branch, since now the PR shows a complete mess  of your commits and mine from the master branch.

**Comment by emodric** [comment]
The easiest way would be to cherry pick them one by one to a new branch created from `3.3-release` and then force push to your `feature/browse-tags` branch on GitHub.

**Comment by JorgenSolli** [comment]
You're right! What a mess 😁 
I'll get this done sometime this week!

**Comment by emodric** [comment]
Replaced by #95

**Pull request closed without merging**
