### PR TITLE
Add isSearchable method and return true

### PR DESCRIPTION
**Pull request by masev**
Like it is indexable in legacy, it should be searchable in newStack

### CODE REVIEW

**Comment by emodric** [comment]
Okay, but what about the actual indexing process? How does it work in Solr & Elastic search?

**Comment by masev** [comment]
Good question ... but I see that every FieldType in core has this method implemented ...
@pspanja maybe you have more information about the impact of this method on futur search system ?

**Comment by masev** [comment]
I suggest that futur search system is handled in the futur as we have no clue about it....

Currently, not adding this method is a problem because when you create a Tags FieldType with the API (or through ReST) it will not be possible to create a searchable FieldType. 
Moreover every implemented FieldType in the core has this method. So this is no harm ...

What do you think @emodric

**Comment by emodric** [comment]
Okay! Merging!

**Comment by masev** [comment]
Great, thanks ;)

**Pull request merged**
