### PR TITLE
Fix erro on eztags required

### PR DESCRIPTION
**Pull request by plesigne**
Hello,

This is a possible fix to https://github.com/netgen/TagsBundle/issues/132

### CODE REVIEW

**Comment by emodric** [comment]
Hi @plesigne !

Thanks for the contribution!

Did you test that this fixes the problem?

**Comment by emodric** [comment]
Tested, working fine. Thanks @plesigne !

**Comment by plesigne** [comment]
Hello @emodric ,

Good news, thx for this project !

**Comment by hgiesenow** [comment]
I think this change breaks the validation in ibexa 3.3, as the selector will not match the markup anymore.
`<div class="ez-field-edit ez-field-edit--eztags ez-field-edit--required is-invalid" tabindex="-1">`
Changing it back returned the functionality of the validation error, when required field is not set.

**Pull request merged**
