### PR TITLE
Update to moved search api namespace

### PR DESCRIPTION
**Pull request by wizhippo**
Should we also move these in the tagsbundle namespace?

### CODE REVIEW

**Comment by emodric** [comment]
Hi,

I would like to wait with this until the new version of eZ Publish is released.

Current `composer install` on `TagsBundle` repo installs eZ Publish 2014.11 as it is the latest stable version. That's why tests for this PR fail with the following error:

```
PHP Fatal error:  Class 'eZ\Publish\Core\Search\Legacy\Content\Common\Gateway\CriterionHandler' not found in /home/travis/build/netgen/TagsBundle/Core/Persistence/Legacy/Content/Search/Common/Gateway/CriterionHandler/TagId.php on line 15
```

**Comment by wizhippo** [comment]
Sounds good

**Comment by Plopix** [comment]
+1 ( we have the error in the 5.4.2 )

**Comment by emodric** [comment]
Hi @Plopix

I'm not really sure how to handle this. I have a [branch](https://github.com/netgen/TagsBundle/tree/search_namespace_rename) which completely fixes the issue together with unit tests, but I can't tag it since the latest eZ Publish Community still uses old namespaces.

**Pull request closed without merging**
