### PR TITLE
Fix PR #138

### PR DESCRIPTION
**Pull request by hgiesenow**
Fixes the wrong change from https://github.com/netgen/TagsBundle/pull/138

### CODE REVIEW

**Comment by emodric** [comment]
@hgiesenow Thanks for your contribution!

Since this is a direct reversal of #138, I would like to hear from @plesigne, the original contributor of #138 to see what he thinks of this. Will this PR break again the issue he was having in #132?

Can you elaborate a bit more? Why do you think change from #138 is wrong?

**Comment by hgiesenow** [comment]
As stated in https://github.com/netgen/TagsBundle/pull/138#issuecomment-1267103732 the fix just made the css selector useless. So the error may go away, together with the functionality it should provide.
In #132 it's all about ibexa 3.2 and 3.1 which are both outdated now. In 3.3 (LTS) my branch is working.

**Comment by emodric** [comment]
Alright, thanks for explanation!

**Comment by alni0** [comment]
Hello,
Not sure to understand why the fix #138 has been reverted, but it seems that I still can reproduce #132 since I upgraded tagsbundle to version 4.0.19...
My Ibexa version is currently 3.3.35 (so LTS version).

Tags feature was working fine with _netgen/tagsbundle_ in version 4.0.18.
But upgrading to 4.0.19 has broken publication validation.
Any content that has a eztags attribute marked as mandatory can not be published any more due to JS error :
image

As selector is still 
image
I indeed don't see how it can be working and which feature was stated (the one supposed to be gone away, but still seems here indeed)..
But maybe I miss something ? (If not I think the fix #138 should be restored ?)

We currently have no other way but to go back to 4.0.18, which implies a lot of dependency limitations..
(or got to branch 5.x but requires upgrade to ibexa 4.x which is another bunch of work)

**Comment by emodric** [comment]
Hi @alni0 !

TagsBundle v4 is not maintained any more, so any fixes for this issue will, unfortunately, not be fixed.

**Comment by alni0** [comment]
Hi @emodric,
Thanks for information and your quick reply !
A pity that this defect has been reintroduced lately (in latest branch version then), but for sure I understand and I will try to find some workaround. And then plan to ugrade to 5.0 branch !

**Pull request merged**
